"""empty message

Revision ID: 7b56f24c6dbe
Revises: 4cb8166123a9
Create Date: 2024-10-28 07:02:08.973562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b56f24c6dbe'
down_revision = '4cb8166123a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('a_treat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=50), nullable=True))

    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=50), nullable=True))

    with op.batch_alter_table('pizza', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=50), nullable=True))

    with op.batch_alter_table('today', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('today', schema=None) as batch_op:
        batch_op.drop_column('foto')

    with op.batch_alter_table('pizza', schema=None) as batch_op:
        batch_op.drop_column('foto')

    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.drop_column('foto')

    with op.batch_alter_table('a_treat', schema=None) as batch_op:
        batch_op.drop_column('foto')

    # ### end Alembic commands ###
